# Generated by Django 4.1.1 on 2022-09-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employee_number',
            field=models.IntegerField(default=0, verbose_name='Кол.во сотрудников'),
        ),
    ]
